name: user_management_app
description: A Flutter User Management Application with MVVM and BLoC
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Dependency Injection
  get_it: ^7.6.4
  dartz: ^0.10.1
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utils
  intl: ^0.18.1
  internet_connection_checker_plus: ^2.9.1+2
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
